import { AccountLevel } from '../middleware/roles.js'

export type AccessRuleGroup =
  | 'dashboard_presence'
  | 'members_personnel'
  | 'badges_temporary_personnel'
  | 'lockup_duty'
  | 'reports_logs'
  | 'admin_configuration'
  | 'system_infrastructure'
  | 'developer_recovery'

export interface AccessRuleDefinition {
  key: string
  label: string
  group: AccessRuleGroup
  builtInDescription: string
  builtInDefaultLevel: AccountLevel
  floorLevel: AccountLevel
}

const BASIC = AccountLevel.BASIC
const QUARTERMASTER = AccountLevel.QUARTERMASTER
const LOCKUP = AccountLevel.LOCKUP
const COMMAND = AccountLevel.COMMAND
const ADMIN = AccountLevel.ADMIN
const DEVELOPER = AccountLevel.DEVELOPER

export const ACCESS_RULE_CATALOG = [
  {
    key: 'dashboard.view',
    label: 'View dashboard',
    group: 'dashboard_presence',
    builtInDescription: 'View the main Sentinel dashboard and presence board.',
    builtInDefaultLevel: BASIC,
    floorLevel: BASIC,
  },
  {
    key: 'presence.viewOccupancy',
    label: 'View building occupancy',
    group: 'dashboard_presence',
    builtInDescription: 'View current building occupancy and presence counts.',
    builtInDefaultLevel: BASIC,
    floorLevel: BASIC,
  },
  {
    key: 'presence.manualCheckout',
    label: 'Manual checkout',
    group: 'dashboard_presence',
    builtInDescription: 'Manually check out an individual present person.',
    builtInDefaultLevel: QUARTERMASTER,
    floorLevel: QUARTERMASTER,
  },
  {
    key: 'presence.bulkCheckout',
    label: 'Bulk administrative checkout',
    group: 'dashboard_presence',
    builtInDescription: 'Administratively clear multiple people or presence records.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'presence.viewHistory',
    label: 'View presence history',
    group: 'dashboard_presence',
    builtInDescription: 'View presence and check-in history.',
    builtInDefaultLevel: ADMIN,
    floorLevel: BASIC,
  },
  {
    key: 'presence.editHistory',
    label: 'Correct presence history',
    group: 'dashboard_presence',
    builtInDescription: 'Edit or correct presence history when operational conditions allow.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'securityAlerts.view',
    label: 'View security alerts',
    group: 'dashboard_presence',
    builtInDescription: 'View active security alerts and alert streams.',
    builtInDefaultLevel: ADMIN,
    floorLevel: COMMAND,
  },
  {
    key: 'securityAlerts.acknowledge',
    label: 'Acknowledge security alerts',
    group: 'dashboard_presence',
    builtInDescription: 'Acknowledge or resolve security alerts.',
    builtInDefaultLevel: COMMAND,
    floorLevel: COMMAND,
  },

  {
    key: 'members.view',
    label: 'View members',
    group: 'members_personnel',
    builtInDescription: 'View routine member records and member lists.',
    builtInDefaultLevel: BASIC,
    floorLevel: BASIC,
  },
  {
    key: 'members.viewAllScopes',
    label: 'View all personnel scopes',
    group: 'members_personnel',
    builtInDescription: 'Include hidden members and all personnel scopes in member views.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'members.viewSensitive',
    label: 'View sensitive member fields',
    group: 'members_personnel',
    builtInDescription: 'View sensitive member details such as service numbers and account levels.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'members.create',
    label: 'Create members',
    group: 'members_personnel',
    builtInDescription: 'Create new member records.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'members.edit',
    label: 'Edit members',
    group: 'members_personnel',
    builtInDescription: 'Edit routine member record details.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'members.archive',
    label: 'Archive members',
    group: 'members_personnel',
    builtInDescription: 'Archive or deactivate member records.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'members.import',
    label: 'Import members',
    group: 'members_personnel',
    builtInDescription: 'Preview and execute member imports.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'members.manageAccountLevels',
    label: 'Manage account levels',
    group: 'members_personnel',
    builtInDescription: 'Assign ordinary Account Levels while respecting escalation guards.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'members.assignDeveloper',
    label: 'Assign Developer account level',
    group: 'members_personnel',
    builtInDescription: 'Assign Developer Account Level to another member.',
    builtInDefaultLevel: DEVELOPER,
    floorLevel: DEVELOPER,
  },
  {
    key: 'members.manageQualifications',
    label: 'Manage member qualifications',
    group: 'members_personnel',
    builtInDescription: 'Manually grant or remove member qualifications.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'members.manageTags',
    label: 'Manage member tags',
    group: 'members_personnel',
    builtInDescription: 'Manually grant or remove member tags.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },

  {
    key: 'badges.view',
    label: 'View badges',
    group: 'badges_temporary_personnel',
    builtInDescription: 'View NFC tag inventory and badge status.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'badges.register',
    label: 'Register badges',
    group: 'badges_temporary_personnel',
    builtInDescription: 'Create or register new NFC tags.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'badges.assignMember',
    label: 'Assign member badges',
    group: 'badges_temporary_personnel',
    builtInDescription: 'Assign or unassign member NFC tags.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'badges.updateStatus',
    label: 'Update badge status',
    group: 'badges_temporary_personnel',
    builtInDescription: 'Mark tags active, lost, returned, or retired.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'badges.archive',
    label: 'Archive badge records',
    group: 'badges_temporary_personnel',
    builtInDescription: 'Perform destructive or archive-style badge record changes.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'temporaryPersonnel.view',
    label: 'View temporary personnel',
    group: 'badges_temporary_personnel',
    builtInDescription: 'View temporary personnel assignments and access state.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'temporaryPersonnel.manageAssignments',
    label: 'Manage temporary assignments',
    group: 'badges_temporary_personnel',
    builtInDescription: 'Create, edit, end, or revoke temporary personnel assignments.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'temporaryPersonnel.assignTags',
    label: 'Assign temporary personnel tags',
    group: 'badges_temporary_personnel',
    builtInDescription: 'Assign or unassign presence-only NFC tags for temporary personnel.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'temporaryPersonnel.recoverTags',
    label: 'Recover temporary personnel tags',
    group: 'badges_temporary_personnel',
    builtInDescription: 'Mark temporary personnel NFC tags as returned after access ends.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },

  {
    key: 'lockup.viewStatus',
    label: 'View lockup status',
    group: 'lockup_duty',
    builtInDescription: 'View current lockup and building status.',
    builtInDefaultLevel: BASIC,
    floorLevel: BASIC,
  },
  {
    key: 'lockup.viewHistory',
    label: 'View lockup history',
    group: 'lockup_duty',
    builtInDescription: 'View lockup transfer and execution history.',
    builtInDefaultLevel: ADMIN,
    floorLevel: LOCKUP,
  },
  {
    key: 'lockup.openBuilding',
    label: 'Open building',
    group: 'lockup_duty',
    builtInDescription: 'Open the building when qualification requirements are also met.',
    builtInDefaultLevel: LOCKUP,
    floorLevel: LOCKUP,
  },
  {
    key: 'lockup.acquire',
    label: 'Acquire lockup',
    group: 'lockup_duty',
    builtInDescription: 'Accept or acquire lockup responsibility when qualified.',
    builtInDefaultLevel: LOCKUP,
    floorLevel: LOCKUP,
  },
  {
    key: 'lockup.transfer',
    label: 'Transfer lockup',
    group: 'lockup_duty',
    builtInDescription: 'Transfer lockup responsibility when qualification and holder rules allow.',
    builtInDefaultLevel: LOCKUP,
    floorLevel: LOCKUP,
  },
  {
    key: 'lockup.execute',
    label: 'Execute building close',
    group: 'lockup_duty',
    builtInDescription: 'Execute building close or lockup when qualified.',
    builtInDefaultLevel: LOCKUP,
    floorLevel: LOCKUP,
  },
  {
    key: 'lockup.adminOverride',
    label: 'Lockup admin override',
    group: 'lockup_duty',
    builtInDescription: 'Use privileged lockup authorization or override paths.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'dds.view',
    label: 'View DDS state',
    group: 'lockup_duty',
    builtInDescription: 'View current DDS state and handover information.',
    builtInDefaultLevel: BASIC,
    floorLevel: BASIC,
  },
  {
    key: 'dds.assign',
    label: 'Assign DDS',
    group: 'lockup_duty',
    builtInDescription: 'Administratively assign, set, transfer, or release DDS.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'dds.accept',
    label: 'Accept DDS',
    group: 'lockup_duty',
    builtInDescription: 'Self-accept DDS when assigned.',
    builtInDefaultLevel: BASIC,
    floorLevel: BASIC,
  },
  {
    key: 'dds.viewAudit',
    label: 'View DDS audit',
    group: 'lockup_duty',
    builtInDescription: 'View DDS audit history.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },

  {
    key: 'reports.viewOperational',
    label: 'View operational reports',
    group: 'reports_logs',
    builtInDescription: 'View or generate routine attendance, presence, visitor, and duty reports.',
    builtInDefaultLevel: ADMIN,
    floorLevel: COMMAND,
  },
  {
    key: 'reports.printOperational',
    label: 'Print operational reports',
    group: 'reports_logs',
    builtInDescription: 'Print or export routine operational reports.',
    builtInDefaultLevel: ADMIN,
    floorLevel: COMMAND,
  },
  {
    key: 'logs.viewAudit',
    label: 'View audit logs',
    group: 'reports_logs',
    builtInDescription: 'View audit activity logs.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'logs.viewRuntime',
    label: 'View runtime logs',
    group: 'reports_logs',
    builtInDescription: 'View live or runtime system logs.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'logs.manageRuntime',
    label: 'Manage runtime logs',
    group: 'reports_logs',
    builtInDescription: 'Change runtime log streaming level or clear runtime log history.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'accessRules.printReport',
    label: 'Print Access Rules report',
    group: 'reports_logs',
    builtInDescription: 'Print or save the Access Rules governance report.',
    builtInDefaultLevel: DEVELOPER,
    floorLevel: DEVELOPER,
  },

  {
    key: 'admin.view',
    label: 'View Admin Control Centre',
    group: 'admin_configuration',
    builtInDescription: 'Enter and view the Admin Control Centre shell.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'adminUsers.view',
    label: 'View admin users',
    group: 'admin_configuration',
    builtInDescription: 'View legacy admin user accounts.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'adminUsers.manage',
    label: 'Manage admin users',
    group: 'admin_configuration',
    builtInDescription: 'Create, edit, enable, disable, or reset legacy admin user accounts.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'adminUsers.delete',
    label: 'Delete admin users',
    group: 'admin_configuration',
    builtInDescription: 'Permanently delete legacy admin user accounts.',
    builtInDefaultLevel: DEVELOPER,
    floorLevel: DEVELOPER,
  },
  {
    key: 'config.view',
    label: 'View configuration',
    group: 'admin_configuration',
    builtInDescription: 'View lists, types, and configuration settings.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'config.settings.manage',
    label: 'Manage general settings',
    group: 'admin_configuration',
    builtInDescription: 'Create, update, or delete general Sentinel settings.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'config.memberTypes.manage',
    label: 'Manage member types',
    group: 'admin_configuration',
    builtInDescription: 'Manage member type definitions.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'config.memberStatuses.manage',
    label: 'Manage member statuses',
    group: 'admin_configuration',
    builtInDescription: 'Manage member status definitions.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'config.qualifications.manage',
    label: 'Manage qualification types',
    group: 'admin_configuration',
    builtInDescription: 'Manage qualification type definitions.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'config.memberTags.manage',
    label: 'Manage member tag definitions',
    group: 'admin_configuration',
    builtInDescription: 'Manage reusable member tag definitions.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'config.visitTypes.manage',
    label: 'Manage visit types',
    group: 'admin_configuration',
    builtInDescription: 'Manage visitor visit type definitions.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'config.eventTypes.manage',
    label: 'Manage event types',
    group: 'admin_configuration',
    builtInDescription: 'Manage event type definitions.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'config.holidays.manage',
    label: 'Manage holidays',
    group: 'admin_configuration',
    builtInDescription: 'Manage statutory holiday and exception definitions.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'config.timing.manage',
    label: 'Manage timings',
    group: 'admin_configuration',
    builtInDescription: 'Manage operational timings, scheduler cutoffs, and alert limits.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'config.display.manage',
    label: 'Manage display settings',
    group: 'admin_configuration',
    builtInDescription: 'Manage dashboard sorting, kiosk sounds, and display-oriented settings.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'accessRules.view',
    label: 'View Access Rules',
    group: 'admin_configuration',
    builtInDescription: 'View the Access Rules policy page.',
    builtInDefaultLevel: DEVELOPER,
    floorLevel: DEVELOPER,
  },
  {
    key: 'accessRules.manage',
    label: 'Manage Access Rules',
    group: 'admin_configuration',
    builtInDescription: 'Edit Access Rule thresholds and local descriptions.',
    builtInDefaultLevel: DEVELOPER,
    floorLevel: DEVELOPER,
  },
  {
    key: 'accessRules.bulkManage',
    label: 'Bulk manage Access Rules',
    group: 'admin_configuration',
    builtInDescription: 'Bulk edit Access Rule thresholds and local descriptions.',
    builtInDefaultLevel: DEVELOPER,
    floorLevel: DEVELOPER,
  },

  {
    key: 'systemHealth.view',
    label: 'View system health',
    group: 'system_infrastructure',
    builtInDescription: 'View appliance and system health status.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'updates.view',
    label: 'View updates',
    group: 'system_infrastructure',
    builtInDescription: 'View installed version, available updates, updater status, and traces.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'updates.apply',
    label: 'Apply updates',
    group: 'system_infrastructure',
    builtInDescription: 'Start or apply system updates.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'network.view',
    label: 'View network state',
    group: 'system_infrastructure',
    builtInDescription: 'View network, hotspot, and remote-system state.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'network.manage',
    label: 'Manage network',
    group: 'system_infrastructure',
    builtInDescription: 'Change network and hotspot settings.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'remoteSystems.view',
    label: 'View remote systems',
    group: 'system_infrastructure',
    builtInDescription: 'View configured remote systems.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'remoteSystems.manage',
    label: 'Manage remote systems',
    group: 'system_infrastructure',
    builtInDescription: 'Create, edit, or disable configured remote systems.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'sessions.view',
    label: 'View active sessions',
    group: 'system_infrastructure',
    builtInDescription: 'View active Sentinel member sessions.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'sessions.revoke',
    label: 'Revoke active sessions',
    group: 'system_infrastructure',
    builtInDescription: 'End or revoke active Sentinel member sessions.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'database.view',
    label: 'View database explorer',
    group: 'system_infrastructure',
    builtInDescription: 'Use the read-only database explorer.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'database.export',
    label: 'Export database',
    group: 'system_infrastructure',
    builtInDescription: 'Export database or Sentinel data.',
    builtInDefaultLevel: DEVELOPER,
    floorLevel: DEVELOPER,
  },
  {
    key: 'backups.create',
    label: 'Create backups',
    group: 'system_infrastructure',
    builtInDescription: 'Create Sentinel backups.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'backups.restore',
    label: 'Restore backups',
    group: 'system_infrastructure',
    builtInDescription: 'Restore Sentinel backups.',
    builtInDefaultLevel: DEVELOPER,
    floorLevel: DEVELOPER,
  },
  {
    key: 'kiosks.viewStatus',
    label: 'View kiosk status',
    group: 'system_infrastructure',
    builtInDescription: 'View kiosk or device status streams.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
  {
    key: 'kiosks.manageDevices',
    label: 'Manage kiosk devices',
    group: 'system_infrastructure',
    builtInDescription: 'Manage kiosk or device authorization.',
    builtInDefaultLevel: ADMIN,
    floorLevel: ADMIN,
  },
] as const satisfies readonly AccessRuleDefinition[]

export type AccessRuleKey = (typeof ACCESS_RULE_CATALOG)[number]['key']

export const ACCESS_RULE_CATALOG_BY_KEY: ReadonlyMap<string, AccessRuleDefinition> = new Map(
  ACCESS_RULE_CATALOG.map((definition) => [definition.key, definition])
)

export function getAccessRuleDefinition(key: string): AccessRuleDefinition | null {
  return ACCESS_RULE_CATALOG_BY_KEY.get(key) ?? null
}
