export const TID = {
  auth: {
    badgeInput: 'auth-badge-input',
    pinInput: 'auth-pin-input',
    pinBack: 'auth-pin-back',
    errorAlert: 'auth-error-alert',
  },
  nav: {
    logo: 'nav-logo',
    link: (page: string) => `nav-link-${page}`,
    helpBtn: 'nav-help-btn',
    backendStatus: 'nav-backend-status',
    backendStatusDetails: 'nav-backend-status-details',
    userMenu: 'nav-user-menu',
    changePin: 'nav-change-pin',
    logout: 'nav-logout',
  },
  sidebar: {
    editBtn: (id: string) => `sidebar-edit-${id}`,
    saveBtn: 'sidebar-save-btn',
    deleteBtn: 'sidebar-delete-btn',
    cancelBtn: 'sidebar-cancel-btn',
  },
  members: {
    syncQualsBtn: 'members-sync-quals-btn',
    importCsvBtn: 'members-import-csv-btn',
    newMemberBtn: 'members-new-member-btn',
    filter: {
      search: 'members-filter-search',
      division: 'members-filter-division',
      rank: 'members-filter-rank',
      status: 'members-filter-status',
      qualification: 'members-filter-qualification',
      clear: 'members-filter-clear',
    },
    table: 'members-table',
    row: (id: string) => `members-row-${id}`,
    rowAction: (id: string, action: string) => `members-row-${id}-${action}`,
    bulk: {
      clear: 'members-bulk-clear',
      edit: 'members-bulk-edit',
      quals: 'members-bulk-quals',
      tags: 'members-bulk-tags',
      delete: 'members-bulk-delete',
    },
    pagination: {
      prev: 'members-page-prev',
      next: 'members-page-next',
      rowsPerPage: 'members-rows-per-page',
      showDeployed: 'members-show-deployed',
    },
    form: {
      modal: 'member-form-modal',
      serviceNumber: 'member-form-service-number',
      rank: 'member-form-rank',
      firstName: 'member-form-first-name',
      lastName: 'member-form-last-name',
      division: 'member-form-division',
      cancel: 'member-form-cancel',
      submit: 'member-form-submit',
    },
  },
  badges: {
    newBadgeBtn: 'badges-new-badge-btn',
    filter: {
      search: 'badges-filter-search',
      status: 'badges-filter-status',
      assignmentType: 'badges-filter-assignment-type',
      clear: 'badges-filter-clear',
    },
    table: 'badges-table',
    row: (id: string) => `badges-row-${id}`,
    rowAction: (id: string, action: string) => `badges-row-${id}-${action}`,
    pagination: {
      prev: 'badges-page-prev',
      next: 'badges-page-next',
      rowsPerPage: 'badges-rows-per-page',
    },
    form: {
      modal: 'badge-form-modal',
      serialNumber: 'badge-form-serial-number',
      status: 'badge-form-status',
      assignmentType: 'badge-form-assignment-type',
      memberSearch: 'badge-form-member-search',
      assignedTo: 'badge-form-assigned-to',
      cancel: 'badge-form-cancel',
      submit: 'badge-form-submit',
    },
  },
  adminUsers: {
    newUserBtn: 'admin-users-new-user-btn',
    errorAlert: 'admin-users-error-alert',
    filter: {
      search: 'admin-users-filter-search',
      role: 'admin-users-filter-role',
      status: 'admin-users-filter-status',
    },
    table: 'admin-users-table',
    row: (id: string) => `admin-users-row-${id}`,
    rowAction: (id: string, action: string) => `admin-users-row-${id}-${action}`,
    pagination: {
      prev: 'admin-users-page-prev',
      next: 'admin-users-page-next',
      rowsPerPage: 'admin-users-rows-per-page',
    },
    form: {
      username: 'admin-users-form-username',
      displayName: 'admin-users-form-display-name',
      role: 'admin-users-form-role',
      email: 'admin-users-form-email',
      firstName: 'admin-users-form-first-name',
      lastName: 'admin-users-form-last-name',
      password: 'admin-users-form-password',
      cancel: 'admin-users-form-cancel',
      submit: 'admin-users-form-submit',
    },
    resetPassword: {
      newPassword: 'admin-users-reset-password-new',
      confirmPassword: 'admin-users-reset-password-confirm',
      cancel: 'admin-users-reset-password-cancel',
      submit: 'admin-users-reset-password-submit',
    },
    status: {
      cancel: 'admin-users-status-cancel',
      confirm: 'admin-users-status-confirm',
    },
  },
  checkins: {
    manualCheckinBtn: 'checkins-manual-checkin-btn',
    filter: {
      startDate: 'checkins-filter-start-date',
      endDate: 'checkins-filter-end-date',
      direction: 'checkins-filter-direction',
      division: 'checkins-filter-division',
      clear: 'checkins-filter-clear',
    },
    table: 'checkins-table',
    row: (id: string) => `checkins-row-${id}`,
    pagination: {
      prev: 'checkins-page-prev',
      next: 'checkins-page-next',
      rowsPerPage: 'checkins-rows-per-page',
    },
    manualModal: {
      memberSearch: 'manual-checkin-member-search',
      clearMember: 'manual-checkin-clear-member',
      memberOption: (id: string) => `manual-checkin-member-${id}`,
      directionIn: 'manual-checkin-direction-in',
      directionOut: 'manual-checkin-direction-out',
      cancel: 'manual-checkin-cancel',
      submit: 'manual-checkin-submit',
    },
  },
  events: {
    createBtn: 'events-create-btn',
    filter: {
      category: 'events-filter-category',
      status: 'events-filter-status',
      startDate: 'events-filter-start-date',
      endDate: 'events-filter-end-date',
      clear: 'events-filter-clear',
    },
    listItem: (id: string) => `events-list-item-${id}`,
    viewBtn: (id: string) => `events-view-${id}`,
    form: {
      title: 'event-form-title',
      type: 'event-form-type',
      date: 'event-form-date',
      startTime: 'event-form-start-time',
      endTime: 'event-form-end-time',
      location: 'event-form-location',
      description: 'event-form-description',
      cancel: 'event-form-cancel',
      submit: 'event-form-submit',
    },
  },
  settings: {
    enumTable: {
      addBtn: 'enum-table-add-btn',
      editBtn: (id: string) => `enum-table-edit-${id}`,
      deleteBtn: (id: string) => `enum-table-delete-${id}`,
      moveUpBtn: (id: string) => `enum-table-move-up-${id}`,
      moveDownBtn: (id: string) => `enum-table-move-down-${id}`,
      deleteConfirm: 'enum-table-delete-confirm',
      deleteCancel: 'enum-table-delete-cancel',
    },
    enumForm: {
      code: 'enum-form-code',
      name: 'enum-form-name',
      description: 'enum-form-description',
      chipVariant: 'enum-form-chip-variant',
      chipColor: 'enum-form-chip-color',
      positional: 'enum-form-positional',
      cancel: 'enum-form-cancel',
      submit: 'enum-form-submit',
    },
    statHoliday: {
      yearSelect: 'stat-holiday-year-select',
      addBtn: 'stat-holiday-add-btn',
      editBtn: (id: string) => `stat-holiday-edit-${id}`,
      deleteBtn: (id: string) => `stat-holiday-delete-${id}`,
      deleteConfirm: 'stat-holiday-delete-confirm',
      deleteCancel: 'stat-holiday-delete-cancel',
    },
  },
  logs: {
    search: 'log-toolbar-search',
    streamLevel: 'log-toolbar-stream-level',
    pauseResumeBtn: 'log-toolbar-pause-resume',
    clearLogsBtn: 'log-toolbar-clear-logs',
    clearFiltersBtn: 'log-toolbar-clear-filters',
    levelToggle: (level: string) => `log-toolbar-level-${level}`,
    moduleToggle: (mod: string) => `log-toolbar-module-${mod}`,
    table: 'log-table',
    row: 'log-row',
  },
  dashboard: {
    help: {
      launcher: 'dashboard-help-launcher',
      toggle: 'dashboard-help-toggle',
      panel: 'dashboard-help-panel',
    },
    quickAction: {
      kiosk: 'quick-action-kiosk',
      manualCheckin: 'quick-action-manual-checkin',
      visitorSignin: 'quick-action-visitor-signin',
      openBuilding: 'quick-action-open-building',
      executeLockup: 'quick-action-execute-lockup',
      transferLockup: 'quick-action-transfer-lockup',
      simulateScan: 'quick-action-simulate-scan',
    },
    kiosk: {
      badgeInput: 'kiosk-badge-input',
      scanSubmit: 'kiosk-scan-submit',
    },
    personCard: (id: string) => `person-card-${id}`,
    visitorCheckout: (id: string) => `person-card-visitor-checkout-${id}`,
  },
} as const
