export const TID = {
  auth: {
    badgeInput: 'auth-badge-input',
    pinInput: 'auth-pin-input',
    pinBack: 'auth-pin-back',
    pinSubmit: 'auth-pin-submit',
    remoteSystemSelect: 'auth-remote-system-select',
    remoteSystemNameInput: 'auth-remote-system-name-input',
    destinationToggle: 'auth-destination-toggle',
    errorAlert: 'auth-error-alert',
    setupNotice: 'auth-setup-notice',
    setupPinInput: 'auth-setup-pin-input',
    setupPinConfirmInput: 'auth-setup-pin-confirm-input',
    setupPinSubmit: 'auth-setup-pin-submit',
    startOfDayPrompt: 'auth-start-of-day-prompt',
    startOfDayOption: (value: string) => `auth-start-of-day-option-${value}`,
    startOfDaySubmit: 'auth-start-of-day-submit',
    startOfDayBack: 'auth-start-of-day-back',
  },
  nav: {
    logo: 'nav-logo',
    remoteSystemBadge: 'nav-remote-system-badge',
    link: (page: string) => `nav-link-${page}`,
    helpBtn: 'nav-help-btn',
    backendStatus: 'nav-backend-status',
    backendStatusDetails: 'nav-backend-status-details',
    backendStatusRecovery: 'nav-backend-status-recovery',
    backendStatusHostRecovery: 'nav-backend-status-host-recovery',
    backendStatusSystemUpdate: 'nav-backend-status-system-update',
    backendStatusRemoteSystems: 'nav-backend-status-remote-systems',
    userMenu: 'nav-user-menu',
    changePin: 'nav-change-pin',
    logout: 'nav-logout',
  },
  sidebar: {
    editBtn: (id: string) => `sidebar-edit-${id}`,
    saveBtn: 'sidebar-save-btn',
    deleteBtn: 'sidebar-delete-btn',
    cancelBtn: 'sidebar-cancel-btn',
  },
  members: {
    syncQualsBtn: 'members-sync-quals-btn',
    importCsvBtn: 'members-import-csv-btn',
    newMemberBtn: 'members-new-member-btn',
    filter: {
      search: 'members-filter-search',
      division: 'members-filter-division',
      rank: 'members-filter-rank',
      status: 'members-filter-status',
      qualification: 'members-filter-qualification',
      clear: 'members-filter-clear',
    },
    table: 'members-table',
    row: (id: string) => `members-row-${id}`,
    rowAction: (id: string, action: string) => `members-row-${id}-${action}`,
    bulk: {
      clear: 'members-bulk-clear',
      edit: 'members-bulk-edit',
      quals: 'members-bulk-quals',
      tags: 'members-bulk-tags',
      delete: 'members-bulk-delete',
    },
    pagination: {
      prev: 'members-page-prev',
      next: 'members-page-next',
      rowsPerPage: 'members-rows-per-page',
      showDeployed: 'members-show-deployed',
      showHidden: 'members-show-hidden',
    },
    form: {
      modal: 'member-form-modal',
      serviceNumber: 'member-form-service-number',
      rank: 'member-form-rank',
      firstName: 'member-form-first-name',
      lastName: 'member-form-last-name',
      division: 'member-form-division',
      cancel: 'member-form-cancel',
      submit: 'member-form-submit',
    },
  },
  badges: {
    newBadgeBtn: 'badges-new-badge-btn',
    filter: {
      search: 'badges-filter-search',
      status: 'badges-filter-status',
      assignmentType: 'badges-filter-assignment-type',
      clear: 'badges-filter-clear',
    },
    table: 'badges-table',
    row: (id: string) => `badges-row-${id}`,
    rowAction: (id: string, action: string) => `badges-row-${id}-${action}`,
    bulk: {
      clear: 'badges-bulk-clear',
      delete: 'badges-bulk-delete',
      decommission: 'badges-bulk-decommission',
    },
    pagination: {
      prev: 'badges-page-prev',
      next: 'badges-page-next',
      rowsPerPage: 'badges-rows-per-page',
      showDecommissioned: 'badges-show-decommissioned',
    },
    form: {
      modal: 'badge-form-modal',
      serialNumber: 'badge-form-serial-number',
      status: 'badge-form-status',
      assignmentType: 'badge-form-assignment-type',
      memberSearch: 'badge-form-member-search',
      assignedTo: 'badge-form-assigned-to',
      cancel: 'badge-form-cancel',
      submit: 'badge-form-submit',
    },
  },
  checkins: {
    manualCheckinBtn: 'checkins-manual-checkin-btn',
    filter: {
      startDate: 'checkins-filter-start-date',
      endDate: 'checkins-filter-end-date',
      direction: 'checkins-filter-direction',
      division: 'checkins-filter-division',
      clear: 'checkins-filter-clear',
    },
    table: 'checkins-table',
    row: (id: string) => `checkins-row-${id}`,
    pagination: {
      prev: 'checkins-page-prev',
      next: 'checkins-page-next',
      rowsPerPage: 'checkins-rows-per-page',
    },
    manualModal: {
      dialog: 'manual-checkin-dialog',
      memberSearch: 'manual-checkin-member-search',
      clearMember: 'manual-checkin-clear-member',
      memberOption: (id: string) => `manual-checkin-member-${id}`,
      directionIn: 'manual-checkin-direction-in',
      directionOut: 'manual-checkin-direction-out',
      cancel: 'manual-checkin-cancel',
      submit: 'manual-checkin-submit',
    },
  },
  events: {
    createBtn: 'events-create-btn',
    filter: {
      category: 'events-filter-category',
      status: 'events-filter-status',
      startDate: 'events-filter-start-date',
      endDate: 'events-filter-end-date',
      clear: 'events-filter-clear',
    },
    listItem: (id: string) => `events-list-item-${id}`,
    viewBtn: (id: string) => `events-view-${id}`,
    form: {
      title: 'event-form-title',
      type: 'event-form-type',
      date: 'event-form-date',
      startTime: 'event-form-start-time',
      endTime: 'event-form-end-time',
      location: 'event-form-location',
      description: 'event-form-description',
      cancel: 'event-form-cancel',
      submit: 'event-form-submit',
    },
  },
  settings: {
    network: {
      tab: 'settings-network-tab',
      saveSsids: 'settings-network-save-ssids',
      resetSsids: 'settings-network-reset-ssids',
      addSsid: 'settings-network-add-ssid',
      ssidInput: (index: number) => `settings-network-ssid-input-${index}`,
      removeSsid: (index: number) => `settings-network-remove-ssid-${index}`,
      addRemoteSystem: 'settings-network-add-remote-system',
      editRemoteSystem: (id: string) => `settings-network-edit-remote-system-${id}`,
      deleteRemoteSystem: (id: string) => `settings-network-delete-remote-system-${id}`,
      toggleRemoteSystem: (id: string) => `settings-network-toggle-remote-system-${id}`,
      moveRemoteSystemUp: (id: string) => `settings-network-move-up-${id}`,
      moveRemoteSystemDown: (id: string) => `settings-network-move-down-${id}`,
      remoteSystemDialog: 'settings-network-remote-system-dialog',
      remoteSystemCode: 'settings-network-remote-system-code',
      remoteSystemName: 'settings-network-remote-system-name',
      remoteSystemDescription: 'settings-network-remote-system-description',
      remoteSystemActive: 'settings-network-remote-system-active',
      remoteSystemSubmit: 'settings-network-remote-system-submit',
      remoteSystemCancel: 'settings-network-remote-system-cancel',
    },
    eventTypes: {
      tab: 'settings-event-types-tab',
      addBtn: 'settings-event-types-add-btn',
      editBtn: (id: string) => `settings-event-types-edit-${id}`,
      deleteBtn: (id: string) => `settings-event-types-delete-${id}`,
      deleteConfirm: 'settings-event-types-delete-confirm',
      deleteCancel: 'settings-event-types-delete-cancel',
    },
    timings: {
      tab: 'settings-timings-tab',
      form: 'settings-timings-form',
      saveBtn: 'settings-timings-save-btn',
      resetBtn: 'settings-timings-reset-btn',
      dayRollover: 'settings-timings-day-rollover',
      lockupWarning: 'settings-timings-lockup-warning',
      lockupCritical: 'settings-timings-lockup-critical',
      dutyWatchAddRule: 'settings-timings-duty-watch-add-rule',
      dutyWatchRuleRow: (ruleId: string) => `settings-timings-duty-watch-rule-row-${ruleId}`,
      dutyWatchRuleEdit: (ruleId: string) => `settings-timings-duty-watch-rule-edit-${ruleId}`,
      dutyWatchRuleDelete: (ruleId: string) => `settings-timings-duty-watch-rule-delete-${ruleId}`,
      dutyWatchEditorName: 'settings-timings-duty-watch-editor-name',
      dutyWatchEditorType: 'settings-timings-duty-watch-editor-type',
      dutyWatchEditorWeekday: 'settings-timings-duty-watch-editor-weekday',
      dutyWatchEditorInterval: 'settings-timings-duty-watch-editor-interval',
      dutyWatchEditorOrdinal: 'settings-timings-duty-watch-editor-ordinal',
      dutyWatchEditorStartDate: 'settings-timings-duty-watch-editor-start-date',
      dutyWatchEditorStartTime: 'settings-timings-duty-watch-editor-start-time',
      dutyWatchEditorEndTime: 'settings-timings-duty-watch-editor-end-time',
      dutyWatchEditorSave: 'settings-timings-duty-watch-editor-save',
      dutyWatchEditorCancel: 'settings-timings-duty-watch-editor-cancel',
      regularStart: 'settings-timings-regular-start',
      regularEnd: 'settings-timings-regular-end',
      summerStartDate: 'settings-timings-summer-start-date',
      summerEndDate: 'settings-timings-summer-end-date',
      summerStart: 'settings-timings-summer-start',
      summerEnd: 'settings-timings-summer-end',
      operationalAlertThreshold: (key: string) => `settings-timings-operational-threshold-${key}`,
      operationalAlertWindow: (key: string) => `settings-timings-operational-window-${key}`,
      securityAlertThreshold: (key: string) => `settings-timings-security-threshold-${key}`,
      securityAlertWindow: (key: string) => `settings-timings-security-window-${key}`,
    },
    enumTable: {
      addBtn: 'enum-table-add-btn',
      editBtn: (id: string) => `enum-table-edit-${id}`,
      deleteBtn: (id: string) => `enum-table-delete-${id}`,
      moveUpBtn: (id: string) => `enum-table-move-up-${id}`,
      moveDownBtn: (id: string) => `enum-table-move-down-${id}`,
      deleteConfirm: 'enum-table-delete-confirm',
      deleteCancel: 'enum-table-delete-cancel',
    },
    enumForm: {
      code: 'enum-form-code',
      name: 'enum-form-name',
      description: 'enum-form-description',
      chipVariant: 'enum-form-chip-variant',
      chipColor: 'enum-form-chip-color',
      positional: 'enum-form-positional',
      cancel: 'enum-form-cancel',
      submit: 'enum-form-submit',
    },
    statHoliday: {
      yearSelect: 'stat-holiday-year-select',
      addBtn: 'stat-holiday-add-btn',
      editBtn: (id: string) => `stat-holiday-edit-${id}`,
      deleteBtn: (id: string) => `stat-holiday-delete-${id}`,
      deleteConfirm: 'stat-holiday-delete-confirm',
      deleteCancel: 'stat-holiday-delete-cancel',
    },
  },
  logs: {
    search: 'log-toolbar-search',
    streamLevel: 'log-toolbar-stream-level',
    pauseResumeBtn: 'log-toolbar-pause-resume',
    clearLogsBtn: 'log-toolbar-clear-logs',
    clearFiltersBtn: 'log-toolbar-clear-filters',
    levelToggle: (level: string) => `log-toolbar-level-${level}`,
    moduleToggle: (mod: string) => `log-toolbar-module-${mod}`,
    table: 'log-table',
    row: 'log-row',
  },
  dashboard: {
    ddsDrawer: {
      open: 'dashboard-dds-drawer-open',
      close: 'dashboard-dds-drawer-close',
      infoLink: 'dashboard-dds-drawer-info-link',
    },
    help: {
      launcher: 'dashboard-help-launcher',
      toggle: 'dashboard-help-toggle',
      panel: 'dashboard-help-panel',
    },
    quickAction: {
      kiosk: 'quick-action-kiosk',
      manualCheckin: 'quick-action-manual-checkin',
      visitorSignin: 'quick-action-visitor-signin',
      openBuilding: 'quick-action-open-building',
      setTodayDds: 'quick-action-set-today-dds',
      executeLockup: 'quick-action-execute-lockup',
      transferLockup: 'quick-action-transfer-lockup',
      simulateScan: 'quick-action-simulate-scan',
    },
    kiosk: {
      launchTab: 'dashboard-kiosk-launch-tab',
      badgeInput: 'kiosk-badge-input',
      scanSubmit: 'kiosk-scan-submit',
      responsibilityPrompt: 'kiosk-responsibility-prompt',
      responsibilityDecline: 'kiosk-responsibility-decline',
      responsibilitySubmit: 'kiosk-responsibility-submit',
    },
    personCard: (id: string) => `person-card-${id}`,
    visitorCheckout: (id: string) => `person-card-visitor-checkout-${id}`,
    memberActions: {
      panel: (id: string) => `dashboard-member-actions-${id}`,
      manualCheckout: (id: string) => `dashboard-member-actions-manual-checkout-${id}`,
      temporaryRole: (id: string) => `dashboard-member-actions-temp-role-${id}`,
      clearTemporaryRole: (id: string) => `dashboard-member-actions-temp-clear-${id}`,
      tonightOverride: (id: string) => `dashboard-member-actions-override-${id}`,
      transferLockup: (id: string) => `dashboard-member-actions-transfer-lockup-${id}`,
      openBuilding: (id: string) => `dashboard-member-actions-open-building-${id}`,
    },
  },
} as const
