-- Migration: Report Audit Log
-- Tracks all report generation for compliance and monitoring (manual and scheduled reports)

-- Report Audit Log table
CREATE TABLE report_audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  report_type VARCHAR(50) NOT NULL,    -- e.g., 'training_night_attendance', 'bmq_attendance', 'daily_checkin_summary'
  report_config JSONB NOT NULL,        -- Filters/parameters used for report generation
  generated_by UUID REFERENCES admin_users(id), -- NULL for scheduled reports
  is_scheduled BOOLEAN DEFAULT false,
  scheduled_report_id UUID,            -- For future scheduled_reports table (Phase 3)
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  file_size_bytes INTEGER,
  generation_time_ms INTEGER
);

CREATE INDEX idx_report_audit_log_type ON report_audit_log(report_type);
CREATE INDEX idx_report_audit_log_generated_by ON report_audit_log(generated_by);
CREATE INDEX idx_report_audit_log_generated_at ON report_audit_log(generated_at);
CREATE INDEX idx_report_audit_log_is_scheduled ON report_audit_log(is_scheduled);

-- Table comments
COMMENT ON TABLE report_audit_log IS 'Audit trail for all report generation (PDF exports, scheduled reports)';
COMMENT ON COLUMN report_audit_log.report_type IS 'Type of report generated (training_night_attendance, bmq_attendance, daily_checkin_summary, personnel_roster, visitor_summary)';
COMMENT ON COLUMN report_audit_log.report_config IS 'JSON object containing report parameters: {division: "OPS", period: "current_year", organizationStyle: "by_division"}';
COMMENT ON COLUMN report_audit_log.generated_by IS 'Admin user who generated the report (null for automated/scheduled reports)';
COMMENT ON COLUMN report_audit_log.is_scheduled IS 'Whether report was auto-generated by scheduler vs manual download';
COMMENT ON COLUMN report_audit_log.scheduled_report_id IS 'Reference to scheduled_reports table (reserved for Phase 3 implementation)';
COMMENT ON COLUMN report_audit_log.file_size_bytes IS 'Size of generated PDF file in bytes';
COMMENT ON COLUMN report_audit_log.generation_time_ms IS 'Time taken to generate report in milliseconds';
