import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEventPresenceData } from '../hooks/useEventPresenceData';
import { EventPresenceCards } from '../components/EventPresenceCards';
import { Clock } from '../components/Clock';
import { ActivityFeed } from '../components/ActivityFeed';
import { ConnectionStatus } from '../components/ConnectionStatus';
export function EventView({ config, eventName }) {
    const { data, isConnected } = useEventPresenceData({ config });
    const connectionStatus = isConnected ? 'bg-emerald-500' : 'bg-red-500';
    const connectionText = isConnected ? 'Connected' : 'Disconnected';
    return (_jsxs("div", { className: "min-h-screen bg-gradient-to-br from-white to-gray-50 tv-mode", children: [_jsxs("div", { className: "flex h-screen", children: [_jsxs("div", { className: "flex-1 p-8 overflow-hidden flex flex-col", children: [_jsxs("div", { className: "flex justify-between items-start mb-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-5xl font-bold text-gray-900 mb-2", children: eventName }), _jsx("p", { className: "text-xl text-gray-600", children: "Event Attendance Overview" }), _jsxs("div", { className: "mt-4 flex items-center gap-2", children: [_jsx("div", { className: `w-4 h-4 rounded-full ${connectionStatus}` }), _jsx("span", { className: "text-lg text-gray-700", children: connectionText })] })] }), _jsx(Clock, {})] }), _jsx("div", { className: "mb-8", children: _jsx(EventPresenceCards, { present: data.present, away: data.away, pending: data.pending }) }), _jsxs("div", { className: "flex-1 overflow-hidden", children: [_jsx("h2", { className: "text-3xl font-bold text-gray-900 mb-6", children: "Attendees" }), _jsx("div", { className: "overflow-y-auto space-y-3 pr-4", children: data.attendees.length === 0 ? (_jsx("p", { className: "text-2xl text-gray-400", children: "No attendees yet..." })) : (data.attendees.map((attendee) => (_jsx("div", { className: `p-4 rounded-lg border-l-4 ${attendee.checkedIn
                                                ? 'bg-emerald-50 border-emerald-500'
                                                : 'bg-gray-50 border-gray-400'}`, children: _jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { children: [_jsxs("div", { className: "text-2xl font-semibold text-gray-900", children: [attendee.rank ? `${attendee.rank} ` : '', attendee.name] }), attendee.division && (_jsx("div", { className: "text-lg text-gray-600 mt-1", children: attendee.division }))] }), attendee.checkedIn && attendee.checkInTime && (_jsx("div", { className: "text-lg text-gray-600 font-mono", children: new Date(attendee.checkInTime).toLocaleTimeString('en-CA', { hour: '2-digit', minute: '2-digit' }) }))] }) }, attendee.id)))) })] })] }), config.activityFeedEnabled && (_jsx("div", { className: "w-[30%] border-l border-gray-200 bg-gray-50", children: _jsx(ActivityFeed, { config: config }) }))] }), _jsx(ConnectionStatus, { isConnected: isConnected })] }));
}
